#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.subset({"kind": "DaemonSet", "metadata": {"name": "prometheus-node-exporter"}})
---
              spec:
                template:
                  #@overlay/match missing_ok=True
                  spec:
                    #@overlay/match by=overlay.all
                    #@overlay/replace
                    serviceAccountName: prometheus-node-exporter
                    containers:
                    - name: prometheus-node-exporter
                      image: harbor-infra.tkg.io/library/prometheus/prometheus_node_exporter:v0.18.1_vmware.1
                      imagePullPolicy: IfNotPresent                      
                      args:
                      - --path.procfs=/host/proc
                      - --path.sysfs=/host/sys
                      - --trim-path-components=3
                      - --watch-file=/mnt/watch/file-9dff78b77fe2f4b0f34f77796df3fea5983e5d4b//var/lib/kubelet/pki/kubelet-client-current.pem
                      - --watch-file=/mnt/watch/file-24d5fa06386fdaf0d20c51e47b92012ea665b9f5//etc/kubernetes/pki/apiserver.crt
                      - --watch-file=/mnt/watch/file-ec8d93d5f83aaefbf9d8c0a3f9643c6bfaffe310//etc/kubernetes/pki/apiserver-etcd-client.crt
                      - --watch-file=/mnt/watch/file-904ae9261099d11adf0c9202070a51aae8a320e2//etc/kubernetes/pki/apiserver-kubelet-client.crt
                      - --watch-file=/mnt/watch/file-15d8ed7db7457d4f5108195ceb52a124a8703898//etc/kubernetes/pki/ca.crt
                      - --watch-file=/mnt/watch/file-99c1687bfbcf4396bdf08131c2971b798d8eb94f//etc/kubernetes/pki/front-proxy-ca.crt
                      - --watch-file=/mnt/watch/file-dfdaa9ca375647a99973f96da9f7fd05a44e5e4f//etc/kubernetes/pki/front-proxy-client.crt
                      - --watch-file=/mnt/watch/file-3642e1c1dd6ed90cba49e7452088e5041441ca65//etc/kubernetes/pki/etcd/ca.crt
                      - --watch-file=/mnt/watch/file-b86beb70611cabc608c7d5c2748d4c7c2850c9bc//etc/kubernetes/pki/etcd/healthcheck-client.crt
                      - --watch-file=/mnt/watch/file-8aab373cf6e572c2c86696ccdb24d0f300e008bb//etc/kubernetes/pki/etcd/peer.crt
                      - --watch-file=/mnt/watch/file-99efa9a2170f5bab53446fc2b983ad325b22a113//etc/kubernetes/pki/etcd/server.crt
                      - --watch-kubeconf=/mnt/watch/kube-35a4fcc6ab089d789fecaeed428cc8392148766a//etc/kubernetes/admin.conf
                      - --watch-kubeconf=/mnt/watch/kube-41a6b8b147ef309a70619cafcfeb8961b3c29cae//etc/kubernetes/controller-manager.conf
                      - --watch-kubeconf=/mnt/watch/kube-ee9e4e203c758bb95ec439d60c16fb4e8854efaf//etc/kubernetes/scheduler.conf
                      - --max-cache-duration=300s
                      ports:
                      - name: metrics
                        containerPort: 9100
                        hostPort: 9100
                      resources: {}
                      volumeMounts:
                      - name: proc
                        mountPath: /host/proc
                        readOnly: true
                      - name: sys
                        mountPath: /host/sys
                        readOnly: true
                      - mountPath: /mnt/watch/file-9dff78b77fe2f4b0f34f77796df3fea5983e5d4b//var/lib/kubelet/pki
                        name: file-9dff78b77fe2f4b0f34f77796df3fea5983e5d4b
                        readOnly: true
                      - mountPath: /mnt/watch/file-24d5fa06386fdaf0d20c51e47b92012ea665b9f5//etc/kubernetes/pki
                        name: file-24d5fa06386fdaf0d20c51e47b92012ea665b9f5
                        readOnly: true
                      - mountPath: /mnt/watch/file-ec8d93d5f83aaefbf9d8c0a3f9643c6bfaffe310//etc/kubernetes/pki
                        name: file-ec8d93d5f83aaefbf9d8c0a3f9643c6bfaffe310
                        readOnly: true
                      - mountPath: /mnt/watch/file-904ae9261099d11adf0c9202070a51aae8a320e2//etc/kubernetes/pki
                        name: file-904ae9261099d11adf0c9202070a51aae8a320e2
                        readOnly: true
                      - mountPath: /mnt/watch/file-15d8ed7db7457d4f5108195ceb52a124a8703898//etc/kubernetes/pki
                        name: file-15d8ed7db7457d4f5108195ceb52a124a8703898
                        readOnly: true
                      - mountPath: /mnt/watch/file-99c1687bfbcf4396bdf08131c2971b798d8eb94f//etc/kubernetes/pki
                        name: file-99c1687bfbcf4396bdf08131c2971b798d8eb94f
                        readOnly: true
                      - mountPath: /mnt/watch/file-dfdaa9ca375647a99973f96da9f7fd05a44e5e4f//etc/kubernetes/pki
                        name: file-dfdaa9ca375647a99973f96da9f7fd05a44e5e4f
                        readOnly: true
                      - mountPath: /mnt/watch/file-3642e1c1dd6ed90cba49e7452088e5041441ca65//etc/kubernetes/pki/etcd
                        name: file-3642e1c1dd6ed90cba49e7452088e5041441ca65
                        readOnly: true
                      - mountPath: /mnt/watch/file-b86beb70611cabc608c7d5c2748d4c7c2850c9bc//etc/kubernetes/pki/etcd
                        name: file-b86beb70611cabc608c7d5c2748d4c7c2850c9bc
                        readOnly: true
                      - mountPath: /mnt/watch/file-8aab373cf6e572c2c86696ccdb24d0f300e008bb//etc/kubernetes/pki/etcd
                        name: file-8aab373cf6e572c2c86696ccdb24d0f300e008bb
                        readOnly: true
                      - mountPath: /mnt/watch/file-99efa9a2170f5bab53446fc2b983ad325b22a113//etc/kubernetes/pki/etcd
                        name: file-99efa9a2170f5bab53446fc2b983ad325b22a113
                        readOnly: true
                      - mountPath: /mnt/watch/kube-35a4fcc6ab089d789fecaeed428cc8392148766a//etc/kubernetes
                        name: kube-35a4fcc6ab089d789fecaeed428cc8392148766a
                        readOnly: true
                      - mountPath: /mnt/watch/kube-41a6b8b147ef309a70619cafcfeb8961b3c29cae//etc/kubernetes
                        name: kube-41a6b8b147ef309a70619cafcfeb8961b3c29cae
                        readOnly: true
                      - mountPath: /mnt/watch/kube-ee9e4e203c758bb95ec439d60c16fb4e8854efaf//etc/kubernetes
                        name: kube-ee9e4e203c758bb95ec439d60c16fb4e8854efaf
                        readOnly: true
                    hostNetwork: false 
                    hostPID: true
                    volumes:
                    - name: proc
                      hostPath:
                        path: /proc
                    - name: sys
                      hostPath:
                        path: /sys

