#@data/values
#@overlay/match-child-defaults missing_ok=True
---
logging:
  image:
    repository: projects.registry.vmware.com/tkg
tkg:
  instance_name: "tkgm"
  cluster_name: "tkc-prod"
fluent_bit:
  output_plugin: "elasticsearch"
  elasticsearch:
    host: "elasticsearch-coordinating-only.elasticsearch.svc.cluster.local"
    port: "9200"
