# fluent-bit k14s objects managed by kapp-controller
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: fluent-bit
  namespace: tanzu-system-logging
  annotations:
    tmc.cloud.vmware.com/managed: "false"
spec:
  syncPeriod: 5m
  serviceAccountName: fluent-bit-extension-sa
  fetch:
    - image:
        url: harbor-infra.tkg.io/library/tkg-extensions-templates:v1.3.1_vmware.1
  template:
    - ytt:
        paths:
          - tkg-extensions/common
          - tkg-extensions/logging/fluent-bit
        inline:
          paths:
            filter-update.yaml: |
              #@ load("@ytt:overlay", "overlay")
              #@overlay/match by=overlay.subset({"kind": "ConfigMap", "metadata": {"name": "fluent-bit-config"}})
              #@overlay/match-child-defaults missing_ok=True
              ---
              data:
                fluent-bit.conf: |
                  [SERVICE]
                      Flush         1
                      Log_Level     info
                      Daemon        off
                      Parsers_File  parsers.conf
                      HTTP_Server   On
                      HTTP_Listen   0.0.0.0
                      HTTP_Port     2020

                  @INCLUDE input-kubernetes.conf
                  @INCLUDE input-kubernetes-event.conf
                  @INCLUDE input-kubernetes-etcd.conf
                  #@INCLUDE input-kubernetes-ingress.conf
                  #@INCLUDE input-kubernetes-harbor.conf
                  @INCLUDE input-systemd.conf
                  @INCLUDE input-kube-apiserver.conf
                  @INCLUDE input-audit.conf
                  @INCLUDE filter-kubernetes.conf
                  @INCLUDE filter-audit.conf
                  @INCLUDE filter-global.conf
                  @INCLUDE filter-record.conf
                  #@INCLUDE filter-tanzu-wavefront.conf
                  @INCLUDE output-elasticsearch-audit.conf
                  @INCLUDE output-elasticsearch-event.conf
                  @INCLUDE output-elasticsearch-ingress.conf
                  @INCLUDE output-elasticsearch-harbor.conf
                  @INCLUDE output-elasticsearch-systemd.conf

                input-kubernetes.conf: |
                  [INPUT]
                      Name              tail
                      Tag               event.kube.*
                      Path              /var/log/containers/*kube-system*.log
                      Parser            cri
                      DB                /var/log/flb_event.db
                      Mem_Buf_Limit     50MB
                      Skip_Long_Lines   On
                      Refresh_Interval  10

                input-kubernetes-event.conf: |
                  [INPUT]
                      Name              tail
                      Tag               event.k8s.*
                      Path              /var/log/containers/event-k8s-event-logger*.log
                      Parser            event
                      DB                /var/log/flb_event.db
                      Mem_Buf_Limit     50MB
                      Skip_Long_Lines   On
                      Refresh_Interval  10

                input-kubernetes-etcd.conf: |
                  [INPUT]
                      Name              tail
                      Tag               event.etcd.*
                      Path              /var/log/containers/*etcd*.log
                      Parser            cri
                      DB                /var/log/flb_etcd.db
                      Mem_Buf_Limit     50MB
                      Skip_Long_Lines   On
                      Refresh_Interval  10

                input-kubernetes-ingress.conf: |
                  [INPUT]
                      Name              tail
                      Tag               ingress.contour.*
                      Path              /var/log/containers/*ingress*.log
                      Parser            cri
                      DB                /var/log/flb_ingress.db
                      Mem_Buf_Limit     50MB
                      Skip_Long_Lines   On
                      Refresh_Interval  10

                input-kubernetes-harbor.conf: |
                  [INPUT]
                      Name              tail
                      Tag               harbor.*
                      Path              /var/log/containers/*harbor*.log
                      Parser            cri
                      DB                /var/log/flb_harbor.db
                      Mem_Buf_Limit     50MB
                      Skip_Long_Lines   On
                      Refresh_Interval  10

                input-systemd.conf: |
                  [INPUT]
                      Name                systemd
                      Tag                 systemd.*
                      Path                /var/log/journal
                      Parser              json
                      DB                  /var/log/flb_kube_systemd.db
                      Systemd_Filter      _SYSTEMD_UNIT=kubelet.service
                      Systemd_Filter      _SYSTEMD_UNIT=containerd.service
                      Read_From_Tail      On
                      Strip_Underscores   On

                input-kube-apiserver.conf: |
                  [INPUT]
                      Name              tail
                      Tag               audit.*
                      Path              /var/log/kubernetes/audit.log
                      Parser            json
                      DB                /var/log/flb_kube_audit.db
                      Mem_Buf_Limit     50MB
                      Refresh_Interval  10
                      Skip_Long_Lines   On

                input-audit.conf: |
                  [INPUT]
                      Name              tail
                      Tag               sysaudit.*
                      Path              /var/log/audit/audit.log
                      Parser            logfmt
                      DB                /var/log/flb_system_audit.db
                      Mem_Buf_Limit     50MB
                      Refresh_Interval  10
                      Skip_Long_Lines   On

                filter-kubernetes.conf: |
                  [FILTER]
                      Name                kubernetes
                      Match               event.*
                      Kube_URL            https://kubernetes.default.svc:443
                      Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                      Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
                      Kube_Tag_Prefix     event.
                      Merge_Log           On
                      Merge_Log_Key       log_processed
                      K8S-Logging.Parser  On
                      K8S-Logging.Exclude On

                filter-tanzu-wavefront.conf: |
                  [FILTER]
                    Name   grep
                    Match  *
                    Exclude $kubernetes['namespace_name'] tkg-system
                    Exclude $kubernetes['namespace_name'] vmware-system-tmc
                    Exclude $kubernetes['namespace_name'] tanzu-system-logging
                    Exclude $kubernetes['namespace_name'] tanzu-system-ingress
                    Exclude $kubernetes['namespace_name'] tanzu-system-registry
                    Exclude $kubernetes['namespace_name'] tanzu-system-monitoring
                    Exclude $kubernetes['namespace_name'] tanzu-observability-saas
                    Exclude $kubernetes['namespace_name'] elasticsearch
                    Exclude $kubernetes['namespace_name'] cert-manager
                    Exclude $kubernetes['namespace_name'] gatekeeper-system
                    Exclude $kubernetes['namespace_name'] kubeapps
                    Exclude $kubernetes['namespace_name'] velero

                filter-audit.conf: |
                  [FILTER]
                      Name                record_modifier
                      Match               audit.*
                      Whitelist_key       auditID
                      Whitelist_key       level
                      Whitelist_key       stage
                      Whitelist_key       requestURI
                      Whitelist_key       sourceIPs
                      Whitelist_key       objectRef
                      Whitelist_key       requestObject
                      Whitelist_key       user
                      Whitelist_key       verb

                filter-global.conf: |
                  [FILTER]
                      Name               grep
                      Match              audit.*
                      Exclude            $user['username'] /.*serviceaccount*./

                filter-record.conf: |
                  [FILTER]
                      Name                record_modifier
                      Match               *
                      Record tkg_cluster azr-sectkgdev
                      Record tkg_instance azr-sectkgdev

                output-elasticsearch-audit.conf: |
                  [OUTPUT]
                      Name            es
                      Match           audit.*
                      Host            elasticsearch-coordinating-only.elasticsearch.svc.cluster.local
                      Port            9200
                      Logstash_Format On
                      Logstash_prefix azr-sectkgdev-audit
                      Logstash_DateFormat %Y.%m.%d
                      Replace_Dots    On
                      Retry_Limit     False
                      Buffer_Size     False
                      tls             Off

                output-elasticsearch-event.conf: |
                  [OUTPUT]
                      Name            es
                      Match           event.*
                      Host            elasticsearch-coordinating-only.elasticsearch.svc.cluster.local
                      Port            9200
                      Logstash_Format On
                      Logstash_prefix azr-sectkgdev-event
                      Logstash_DateFormat %Y.%m.%d
                      Replace_Dots    On
                      Retry_Limit     False
                      Buffer_Size     False
                      tls             Off

                output-elasticsearch-ingress.conf: |
                  [OUTPUT]
                      Name            es
                      Match           ingress.*
                      Host            elasticsearch-coordinating-only.elasticsearch.svc.cluster.local
                      Port            9200
                      Logstash_Format On
                      Logstash_prefix azr-sectkgdev-ingress
                      Logstash_DateFormat %Y.%m.%d
                      Replace_Dots    On
                      Retry_Limit     False
                      Buffer_Size     False
                      tls             Off

                output-elasticsearch-harbor.conf: |
                  [OUTPUT]
                      Name            es
                      Match           harbor.*
                      Host            elasticsearch-coordinating-only.elasticsearch.svc.cluster.local
                      Port            9200
                      Logstash_Format On
                      Logstash_prefix azr-sectkgdev-harbor
                      Logstash_DateFormat %Y.%m.%d
                      Replace_Dots    On
                      Retry_Limit     False
                      Buffer_Size     False
                      tls             Off

                output-elasticsearch-systemd.conf: |
                  [OUTPUT]
                      Name            es
                      Match           systemd.*
                      Host            elasticsearch-coordinating-only.elasticsearch.svc.cluster.local
                      Port            9200
                      Logstash_Format On
                      Logstash_prefix azr-sectkgdev-systemd
                      Logstash_DateFormat %Y.%m.%d
                      Replace_Dots    On
                      Retry_Limit     False
                      Buffer_Size     False
                      tls             Off

                parsers.conf: |
                  [PARSER]
                      Name   apache
                      Format regex
                      Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
                      Time_Key time
                      Time_Format %d/%b/%Y:%H:%M:%S %z

                  [PARSER]
                      Name   apache2
                      Format regex
                      Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^ ]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
                      Time_Key time
                      Time_Format %d/%b/%Y:%H:%M:%S %z

                  [PARSER]
                      Name   apache_error
                      Format regex
                      Regex  ^\[[^ ]* (?<time>[^\]]*)\] \[(?<level>[^\]]*)\](?: \[pid (?<pid>[^\]]*)\])?( \[client (?<client>[^\]]*)\])? (?<message>.*)$

                  [PARSER]
                      Name   nginx
                      Format regex
                      Regex ^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
                      Time_Key time
                      Time_Format %d/%b/%Y:%H:%M:%S %z

                  [PARSER]
                      Name   json
                      Format json
                      Time_Key time
                      Time_Format %d/%b/%Y:%H:%M:%S %z

                  [PARSER]
                      Name        docker
                      Format      json
                      Time_Key    time
                      Time_Format %Y-%m-%dT%H:%M:%S.%L
                      Time_Keep   On

                  [PARSER]
                      Name        docker-daemon
                      Format      regex
                      Regex       time="(?<time>[^ ]*)" level=(?<level>[^ ]*) msg="(?<msg>[^ ].*)"
                      Time_Key    time
                      Time_Format %Y-%m-%dT%H:%M:%S.%L
                      Time_Keep   On

                  [PARSER]
                      # http://rubular.com/r/tjUt3Awgg4
                      Name cri
                      Format regex
                      Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>.*)$
                      Time_Key    time
                      Time_Format %Y-%m-%dT%H:%M:%S.%L%z

                  [PARSER]
                      Name event
                      Format regex
                      regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<metadata>.*)kind":"(?<kind>.*)","namespace":"(?<namespace>.*)","name":"(?<deploy_name>.*)","uid(?<uid>.*)apiVersion":"(?<apiversion>.*)reason":"(?<reason>.*)","message":"(?<message>.*)","source":{"component":"(?<component>.*)"},"firstTimestamp":"(?<fristTimestamp>.*)","lastTimestamp":"(?<lastTimestamp>.*)","count":(?<count>.*),"type":"(?<type>.*)","eventTime":(?<eventTime>.*),"reportingComponent":(?<reportingComponent>.*)(?<reportingInstance>.*)
                      Time_Key    time
                      Time_Format %Y-%m-%dT%H:%M:%S.%L%z

                  [PARSER]
                      Name        logfmt
                      Format      logfmt

                  [PARSER]
                      Name        syslog-rfc5424
                      Format      regex
                      Regex       ^\<(?<pri>[0-9]{1,5})\>1 (?<time>[^ ]+) (?<host>[^ ]+) (?<ident>[^ ]+) (?<pid>[-0-9]+) (?<msgid>[^ ]+) (?<extradata>(\[(.*)\]|-)) (?<message>.+)$
                      Time_Key    time
                      Time_Format %Y-%m-%dT%H:%M:%S.%L
                      Time_Keep   On

                  [PARSER]
                      Name        syslog-rfc3164-local
                      Format      regex
                      Regex       ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
                      Time_Key    time
                      Time_Format %b %d %H:%M:%S
                      Time_Keep   On

                  [PARSER]
                      Name        syslog-rfc3164
                      Format      regex
                      Regex       /^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$/
                      Time_Key    time
                      Time_Format %b %d %H:%M:%S
                      Time_Format %Y-%m-%dT%H:%M:%S.%L
                      Time_Keep   On

                  [PARSER]
                      Name    kube-custom
                      Format  regex
                      Regex   (?<tag>[^.]+)?\.?(?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-(?<docker_id>[a-z0-9]{64})\.log$

          pathsFrom:
            - secretRef:
                name: fluent-bit-data-values
  deploy:
    - kapp:
        rawOptions: ["--wait-timeout=5m"]

