#! The namespace in which to deploy ExternalDNS.
namespace: tanzu-system-service-discovery

#! Deployment related configuration
deployment:
  #! (REQUIRED) Args passed via command-line to external-dns
  #! For more guidance on configuration options for your desired DNS provider, consult the
  #! ExternalDNS docs at https://github.com/kubernetes-sigs/external-dns#running-externaldns
  args:
    - --domain-filter=tkg.io # For example, k8s.example.org. Makes ExternalDNS see only the hosted zones matching provided domain, omit to process all available hosted zones.
    - --policy=upsert-only # Prevents ExternalDNS from deleting any records, omit to enable full synchronization.
    - --registry=txt
    - --txt-owner-id=k8s
    - --txt-prefix=external-dns- # Disambiguates TXT records from CNAME records.
    - --provider=rfc2136
    - --rfc2136-host=ldaps.tkg.io
    - --rfc2136-port=53
    - --rfc2136-zone=tkg.io
    - --rfc2136-gss-tsig
    - --rfc2136-kerberos-realm=tkg.io
    - --rfc2136-kerberos-username=administrator  # AD USERNAME
    - --rfc2136-kerberos-password=               # AD PASSWORD
    - --rfc2136-tsig-axfr
    - --source=service
    - --source=ingress
    - --source=contour-httpproxy # Provide this to enable Contour HTTPProxy support. Must have Contour installed or ExternalDNS will fail.
  # - --rfc2136-tsig-secret=TSIG-SECRET-FROM-STEP-1
  # - --rfc2136-tsig-secret-alg=hmac-sha256
  # - --rfc2136-tsig-keyname=TSIG-KEY-NAME # For example, externaldns-key.
  #! Environment variables to pass to external-dns
  env: []
  #! Security context of the external-dns container
  securityContext: {}
  #! Volume mounts of the external-dns container
  volumeMounts:
  - name: kerberos-config-volume
    mountPath: /etc/krb5.conf
    subPath: krb5.conf
  #! Volume of the external-dns pod
  volumes:
  - name: kerberos-config-volume
    configMap:
      defaultMode: 420
      name: krb5.conf